'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NetSige.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Approve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Approve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Attach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CostSharing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CostSharing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM COSTSHARING
        '''WHERE COSTSHARING.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property CostSharingDelete() As String
            Get
                Return ResourceManager.GetString("CostSharingDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    COSTSHARING.ID,
        '''    CASE COSTSHARING.STATUSID
        '''        WHEN 0 THEN &apos;Ativo&apos;
        '''        WHEN 1 THEN &apos;Inativo&apos;
        '''    END AS &apos;Status&apos;,
        '''    STRFTIME(&apos;%d/%m/%Y&apos;, COSTSHARING.CREATIONDATE) As &apos;Data&apos;,
        '''    COSTSHARING.NAME AS &apos;Nome&apos;,
        '''    COSTSHARING.BUSINESSNAME AS &apos;Nome Fantasia&apos;,
        '''    COSTSHARING.DOCUMENT1 AS &apos;CPF/CNPJ&apos;,
        '''    COSTSHARING.DOCUMENT2 AS &apos;Insc. Estadual&apos;,
        '''    COSTSHARING.DOCUMENT3 AS &apos;Insc. Municipal&apos;,
        '''    COSTSHARING.ZIPCODE AS &apos;Cep&apos;,    
        '''    COSTSHARING.ADDRESS AS &apos;Endereço&apos;,
        '''    COSTSHARING.NUMB [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property CostSharingFilter() As String
            Get
                Return ResourceManager.GetString("CostSharingFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO COSTSHARING
        ''' (
        '''    STATUSID,
        '''    CREATIONDATE,
        '''    LOGOPATH,
        '''    NAME,
        '''    BUSINESSNAME,
        '''    DOCUMENT1,
        '''    DOCUMENT2,
        '''    DOCUMENT3,
        '''    ZIPCODE,
        '''    ADDRESS,
        '''    NUMBER,
        '''    COMPLEMENT,
        '''    DISTRICT,
        '''    CITY,
        '''    STATE,
        '''    NOTE,
        '''    USERID
        ''' )
        '''VALUES
        ''' (
        '''    @STATUSID,
        '''    @CREATIONDATE,
        '''    @LOGOPATH,
        '''    @NAME,
        '''    @BUSINESSNAME,
        '''    @DOCUMENT1,
        '''    @DOCUMENT2,
        '''    @DOCUMENT3,
        '''    @ZIPCODE,
        '''    @ADDRESS,
        '''    @NUMBER,
        '''    @COMPLEMENT,
        '''    @DISTRICT,
        '''    @CITY,
        '''    @STATE,
        '''    @NOTE,
        '''    @USER [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property CostSharingInsert() As String
            Get
                Return ResourceManager.GetString("CostSharingInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE COSTSHARING SET
        '''    LASTLOCALSEQ = @LASTLOCALSEQ
        '''WHERE COSTSHARING.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property CostSharingLastLocalSeqUpdate() As String
            Get
                Return ResourceManager.GetString("CostSharingLastLocalSeqUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM COSTSHARINGLOCAL
        '''WHERE COSTSHARINGLOCAL.COSTSHARINGID = @COSTSHARINGID
        '''    AND COSTSHARINGLOCAL.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property CostSharingLocalDelete() As String
            Get
                Return ResourceManager.GetString("CostSharingLocalDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO COSTSHARINGLOCAL
        ''' (
        '''    SEQ,
        '''    COSTSHARINGID,
        '''    NAME,
        '''    ZIPCODE,
        '''    ADDRESS,
        '''    NUMBER,
        '''    COMPLEMENT,
        '''    DISTRICT,
        '''    CITY,
        '''    STATE,
        '''    PHONE,
        '''    EMAIL
        ''' )
        '''VALUES
        ''' (
        '''    @SEQ,
        '''    @COSTSHARINGID,
        '''    @NAME,
        '''    @ZIPCODE,
        '''    @ADDRESS,
        '''    @NUMBER,
        '''    @COMPLEMENT,
        '''    @DISTRICT,
        '''    @CITY,
        '''    @STATE,
        '''    @PHONE,
        '''    @EMAIL
        ''' );.
        '''</summary>
        Friend ReadOnly Property CostSharingLocalInsert() As String
            Get
                Return ResourceManager.GetString("CostSharingLocalInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    COSTSHARING.LASTLOCALSEQ FROM COSTSHARING WHERE COSTSHARING.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property CostSharingLocalLastSeq() As String
            Get
                Return ResourceManager.GetString("CostSharingLocalLastSeq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    COSTSHARINGLOCAL.ID,
        '''    COSTSHARINGLOCAL.SEQ,
        '''    COSTSHARINGLOCAL.COSTSHARINGID,
        '''    COSTSHARINGLOCAL.NAME,
        '''    COSTSHARINGLOCAL.ZIPCODE,
        '''    COSTSHARINGLOCAL.ADDRESS,
        '''    COSTSHARINGLOCAL.NUMBER,
        '''    COSTSHARINGLOCAL.COMPLEMENT,
        '''    COSTSHARINGLOCAL.DISTRICT,
        '''    COSTSHARINGLOCAL.CITY,
        '''    COSTSHARINGLOCAL.STATE,
        '''    COSTSHARINGLOCAL.PHONE,
        '''    COSTSHARINGLOCAL.EMAIL
        '''FROM     COSTSHARINGLOCAL
        '''WHERE     COSTSHARINGLOCAL.COSTSHARINGID = @ID;.
        '''</summary>
        Friend ReadOnly Property CostSharingLocalSelect() As String
            Get
                Return ResourceManager.GetString("CostSharingLocalSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE COSTSHARINGLOCAL SET
        '''    NAME = @NAME,
        '''    ZIPCODE = @ZIPCODE,
        '''    ADDRESS = @ADDRESS,
        '''    NUMBER = @NUMBER,
        '''    COMPLEMENT = @COMPLEMENT,
        '''    DISTRICT = @DISTRICT,
        '''    CITY = @CITY,
        '''    STATE = @STATE,
        '''    PHONE = @PHONE,
        '''    EMAIL = @EMAIL
        '''WHERE COSTSHARINGLOCAL.COSTSHARINGID = @COSTSHARINGID
        '''     AND COSTSHARINGLOCAL.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property CostSharingLocalUpdate() As String
            Get
                Return ResourceManager.GetString("CostSharingLocalUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    COSTSHARING.ID,
        '''    COSTSHARING.STATUSID,
        '''    COSTSHARING.CREATIONDATE,
        '''    COSTSHARING.LOGOPATH,
        '''    COSTSHARING.NAME,
        '''    COSTSHARING.BUSINESSNAME,
        '''    COSTSHARING.DOCUMENT1,
        '''    COSTSHARING.DOCUMENT2,
        '''    COSTSHARING.DOCUMENT3,
        '''    COSTSHARING.ZIPCODE,
        '''    COSTSHARING.ADDRESS,
        '''    COSTSHARING.NUMBER,
        '''    COSTSHARING.COMPLEMENT,
        '''    COSTSHARING.DISTRICT,
        '''    COSTSHARING.CITY,
        '''    COSTSHARING.STATE,
        '''    COSTSHARING.NOTE,
        '''    COSTSHARING.USERID
        '''FROM 
        '''    COSTSHARING
        '''WHERE
        '''    COSTSHARING.ID = @ID [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property CostSharingSelect() As String
            Get
                Return ResourceManager.GetString("CostSharingSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE COSTSHARING SET
        '''    STATUSID = @STATUSID,
        '''    LOGOPATH = @LOGOPATH,
        '''    NAME = @NAME,
        '''    BUSINESSNAME = @BUSINESSNAME,
        '''    DOCUMENT1 = @DOCUMENT1,
        '''    DOCUMENT2 = @DOCUMENT2,
        '''    DOCUMENT3 = @DOCUMENT3,
        '''    ZIPCODE = @ZIPCODE,
        '''    ADDRESS = @ADDRESS,
        '''    NUMBER = @NUMBER,
        '''    COMPLEMENT = @COMPLEMENT,
        '''    DISTRICT = @DISTRICT,
        '''    CITY = @CITY,
        '''    STATE = @STATE,
        '''    NOTE = @NOTE,
        '''    USERID = @USERID
        '''WHERE
        '''    COSTSHARING.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property CostSharingUpdate() As String
            Get
                Return ResourceManager.GetString("CostSharingUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DeleteSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Disapprove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disapprove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EditSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EditSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FilterSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilterSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FinalizeItem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FinalizeItem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property History() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("History", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM HISTORY
        '''WHERE HISTORY.ROUTINEID = @ROUTINEID
        '''    AND REGISTRY = @REGISTRY;.
        '''</summary>
        Friend ReadOnly Property HistoryDelete() As String
            Get
                Return ResourceManager.GetString("HistoryDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    USER.USERNAME AS &apos;Usuário&apos;,
        '''    HISTORY.FIELD AS &apos;Campo&apos;,
        '''    HISTORY.OLDVALUE AS &apos;Valor Antigo&apos;,
        '''    HISTORY.NEWVALUE AS &apos;Valor Novo&apos;,
        '''    STRFTIME(&apos;%d/%m/%Y às %H:%i:%s&apos;, HISTORY.CHANGEDATE) AS &apos;Data&apos;
        '''FROM HISTORY
        '''LEFT JOIN USER ON USER.ID = HISTORY.USERID
        '''WHERE HISTORY.ROUTINEID = @ROUTINEID
        '''    AND HISTORY.REGISTRY = @REGISTRY;.
        '''</summary>
        Friend ReadOnly Property HistorySelect() As String
            Get
                Return ResourceManager.GetString("HistorySelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Include() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Include", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IncludeSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM ITEM
        '''WHERE ITEM.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property ItemDelete() As String
            Get
                Return ResourceManager.GetString("ItemDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    ITEM.ID,
        '''    CASE ITEM.STATUSID
        '''        WHEN 0 THEN &apos;Ativo&apos;
        '''        WHEN 1 THEN &apos;Inativo&apos;
        '''    END AS &apos;Status&apos;,
        '''    STRFTIME(&apos;%d/%m/%Y&apos;, ITEM.CREATIONDATE) AS &apos;Data&apos;,
        '''    ITEM.NAME AS &apos;Nome&apos;,
        '''    ITEMUNIT.INITIALS AS &apos;Unidade&apos;,
        '''    ITEMGROUP.NAME AS &apos;Grupo&apos;,
        '''    ITEM.INTERNALCODE AS &apos;Cód. Interno&apos;,
        '''    ITEM.MANUFACTURER AS &apos;Fabricante&apos;,
        '''    ITEM.MANUFACTURERCODE AS &apos;Cód. Fabricante&apos;,
        '''    ITEM.NOTE AS &apos;Observação&apos;
        '''FROM ITEM
        '''LEFT JOIN ITEMUNIT ON ITEMUNIT.ID = ITEM.ITEMUNITID
        '''LEFT JOIN ITEMGROUP ON  [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ItemFilter() As String
            Get
                Return ResourceManager.GetString("ItemFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ItemGroup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ItemGroup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM ITEMGROUP
        '''WHERE ITEMGROUP.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property ItemGroupDelete() As String
            Get
                Return ResourceManager.GetString("ItemGroupDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    ITEMGROUP.ID,
        '''    CASE ITEMGROUP.STATUSID
        '''        WHEN 0 THEN &apos;Ativo&apos;
        '''        WHEN 1 THEN &apos;Inativo&apos;
        '''    END AS &apos;Status&apos;,
        '''    STRFTIME(&apos;%d/%m/%Y&apos;, ITEMGROUP.CREATIONDATE) As &apos;Data&apos;,
        '''    ITEMGROUP.NAME AS &apos;Nome&apos;
        '''FROM ITEMGROUP
        '''WHERE
        '''    IFNULL(ITEMGROUP.ID, &apos;&apos;) LIKE @ID AND
        '''    IFNULL(ITEMGROUP.STATUSID, &apos;&apos;) LIKE @STATUSID AND
        '''    IFNULL(ITEMGROUP.NAME, &apos;&apos;) LIKE @NAME AND
        '''    ITEMGROUP.CREATIONDATE BETWEEN @CREATIONDATEI AND @CREATIONDATEF;.
        '''</summary>
        Friend ReadOnly Property ItemGroupFilter() As String
            Get
                Return ResourceManager.GetString("ItemGroupFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO ITEMGROUP
        '''(
        '''    STATUSID,
        '''    CREATIONDATE,
        '''    NAME,
        '''    USERID
        ''')
        '''VALUES
        '''(
        '''    @STATUSID,
        '''    @CREATIONDATE,
        '''    @NAME,
        '''    @USERID
        ''');.
        '''</summary>
        Friend ReadOnly Property ItemGroupInsert() As String
            Get
                Return ResourceManager.GetString("ItemGroupInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    ITEMGROUP.ID,
        '''    ITEMGROUP.STATUSID,
        '''    ITEMGROUP.CREATIONDATE,
        '''    ITEMGROUP.NAME,
        '''    ITEMGROUP.USERID
        '''FROM
        '''    ITEMGROUP
        '''WHERE
        '''    ITEMGROUP.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property ItemGroupSelect() As String
            Get
                Return ResourceManager.GetString("ItemGroupSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE ITEMGROUP SET
        '''    STATUSID = @STATUSID,
        '''    NAME = @NAME,
        '''    USERID = @USERID
        '''WHERE
        '''    ID = @ID;.
        '''</summary>
        Friend ReadOnly Property ItemGroupUpdate() As String
            Get
                Return ResourceManager.GetString("ItemGroupUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO ITEM
        '''(
        '''    STATUSID,
        '''    CREATIONDATE,
        '''    PHOTOPATH,
        '''    NAME,
        '''    ITEMUNITID,
        '''    ITEMGROUPID,
        '''    INTERNALCODE,
        '''    MANUFACTURER,
        '''    MANUFACTURERCODE,
        '''    NOTE,
        '''    USERID
        ''')
        '''VALUES
        '''(
        '''    @STATUSID,
        '''    @CREATIONDATE,
        '''    @PHOTOPATH,
        '''    @NAME,
        '''    @ITEMUNIT,
        '''    @ITEMGROUP,
        '''    @INTERNALCODE,
        '''    @MANUFACTURER,
        '''    @MANUFACTURERCODE,
        '''    @NOTE,
        '''    @USERID
        ''');.
        '''</summary>
        Friend ReadOnly Property ItemInsert() As String
            Get
                Return ResourceManager.GetString("ItemInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    ITEM.ID,
        '''    ITEM.STATUSID,
        '''    ITEM.CREATIONDATE,
        '''    ITEM.PHOTOPATH,
        '''    ITEM.NAME,
        '''    ITEM.ITEMUNITID,
        '''    ITEM.ITEMGROUPID,
        '''    ITEM.INTERNALCODE,
        '''    ITEM.MANUFACTURER,
        '''    ITEM.MANUFACTURERCODE,
        '''    ITEM.NOTE,
        '''    ITEM.USERID
        '''FROM
        '''    ITEM
        '''WHERE
        '''    ITEM.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property ItemSelect() As String
            Get
                Return ResourceManager.GetString("ItemSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    PURCHASEORDER.ID PURCHASEORDER,
        '''    STRFTIME(&apos;%d/%m/%Y&apos;, PURCHASEORDER.CREATIONDATE) As &apos;CREATIONDATE&apos;,
        '''    PERSON.NAME PERSON,
        '''    ITEMUNIT.INITIALS UNIT,
        '''    PURCHASEORDERITEM.QUANTITY/100 AS QUANTITY,
        '''    PURCHASEORDERITEM.PRICE/100 AS PRICE,
        '''    CAST(PURCHASEORDERITEM.IPI AS REAL)/100 AS IPI
        '''FROM PURCHASEORDERITEM
        '''LEFT JOIN PURCHASEORDER ON PURCHASEORDER.ID = PURCHASEORDERITEM.PURCHASEORDERID
        '''LEFT JOIN PERSON ON PERSON.ID = PURCHASEORDER.PERSONID
        '''LEFT JOIN ITEM ON ITEM.ID = PURCHAS [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ItemTransactions() As String
            Get
                Return ResourceManager.GetString("ItemTransactions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ItemUnit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ItemUnit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM ITEMUNIT
        '''WHERE ITEMUNIT.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property ItemUnitDelete() As String
            Get
                Return ResourceManager.GetString("ItemUnitDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    ITEMUNIT.ID,
        '''    CASE ITEMUNIT.STATUSID
        '''        WHEN 0 THEN &apos;Ativo&apos;
        '''        WHEN 1 THEN &apos;Inativo&apos;
        '''    END AS &apos;Status&apos;,
        '''    STRFTIME(&apos;%d/%m/%Y&apos;, ITEMUNIT.CREATIONDATE) As &apos;Data&apos;,
        '''    ITEMUNIT.NAME AS &apos;Nome&apos;,
        '''    ITEMUNIT.INITIALS AS &apos;Sigla&apos;
        '''FROM ITEMUNIT
        '''WHERE
        '''    IFNULL(ITEMUNIT.ID, &apos;&apos;) LIKE @ID AND
        '''    IFNULL(ITEMUNIT.STATUSID, &apos;&apos;) LIKE @STATUSID AND
        '''    IFNULL(ITEMUNIT.NAME, &apos;&apos;) LIKE @NAME AND
        '''    IFNULL(ITEMUNIT.INITIALS, &apos;&apos;) LIKE @INITIALS AND
        '''    ITEMUNIT.CREATIONDATE BETWEEN @CREATIONDATEI  [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ItemUnitFilter() As String
            Get
                Return ResourceManager.GetString("ItemUnitFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO ITEMUNIT
        '''(
        '''    STATUSID,
        '''    CREATIONDATE,
        '''    NAME,
        '''    INITIALS,
        '''    USERID
        ''')
        '''VALUES
        '''(
        '''    @STATUSID,
        '''    @CREATIONDATE,
        '''    @NAME,
        '''    @INITIALS,
        '''    @USERID
        ''');.
        '''</summary>
        Friend ReadOnly Property ItemUnitInsert() As String
            Get
                Return ResourceManager.GetString("ItemUnitInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    ITEMUNIT.ID,
        '''    ITEMUNIT.STATUSID,
        '''    ITEMUNIT.CREATIONDATE,
        '''    ITEMUNIT.NAME,
        '''    ITEMUNIT.INITIALS,
        '''    ITEMUNIT.USERID
        '''FROM ITEMUNIT
        '''WHERE ITEMUNIT.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property ItemUnitSelect() As String
            Get
                Return ResourceManager.GetString("ItemUnitSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE ITEMUNIT SET
        '''    STATUSID = @STATUSID,
        '''    NAME = @NAME,
        '''    INITIALS = @INITIALS,
        '''    USERID = @USERID
        '''WHERE ITEMUNIT.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property ItemUnitUpdate() As String
            Get
                Return ResourceManager.GetString("ItemUnitUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE ITEM SET
        '''    STATUSID = @STATUSID,
        '''    PHOTOPATH = @PHOTOPATH,
        '''    NAME = @NAME,
        '''    ITEMUNITID = @ITEMUNIT,
        '''    ITEMGROUPID = @ITEMGROUP,
        '''    INTERNALCODE = @INTERNALCODE,
        '''    MANUFACTURER = @MANUFACTURER,
        '''    MANUFACTURERCODE = @MANUFACTURERCODE,
        '''    NOTE = @NOTE,
        '''    USERID = @USERID
        '''WHERE
        '''    ID = @ID;.
        '''</summary>
        Friend ReadOnly Property ItemUpdate() As String
            Get
                Return ResourceManager.GetString("ItemUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavFirst() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavFirst", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavLast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavLast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavPrevious() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavPrevious", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Panels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Panels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PaymentTerm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaymentTerm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM PAYMENTTERMDAY
        '''WHERE PAYMENTTERMDAY.PAYMENTTERMID = @PAYMENTTERMID
        '''    AND PAYMENTTERMDAY.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PaymentTermDayDelete() As String
            Get
                Return ResourceManager.GetString("PaymentTermDayDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO PAYMENTTERMDAY
        ''' (
        '''    PAYMENTTERMID,
        '''    DAYS
        ''' )
        '''VALUES
        ''' (
        '''    @PAYMENTTERMID,
        '''    @DAYS
        ''' );.
        '''</summary>
        Friend ReadOnly Property PaymentTermDayInsert() As String
            Get
                Return ResourceManager.GetString("PaymentTermDayInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    PAYMENTTERMDAY.ID,
        '''    PAYMENTTERMDAY.PAYMENTTERMID,
        '''    PAYMENTTERMDAY.DAYS
        '''FROM PAYMENTTERMDAY
        '''WHERE PAYMENTTERMDAY.PAYMENTTERMID = @ID;.
        '''</summary>
        Friend ReadOnly Property PaymentTermDaySelect() As String
            Get
                Return ResourceManager.GetString("PaymentTermDaySelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PAYMENTTERMDAY SET
        '''    DAYS = @DAYS
        '''WHERE PAYMENTTERMID = @PAYMENTTERMID
        '''    AND PAYMENTTERMDAY.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PaymentTermDayUpdate() As String
            Get
                Return ResourceManager.GetString("PaymentTermDayUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM PAYMENTTERM
        '''WHERE PAYMENTTERM.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PaymentTermDelete() As String
            Get
                Return ResourceManager.GetString("PaymentTermDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    PAYMENTTERM.ID,
        '''    CASE PAYMENTTERM.STATUSID
        '''        WHEN 0 THEN &apos;Ativo&apos;
        '''        WHEN 1 THEN &apos;Inativo&apos;
        '''    END AS &apos;Status&apos;,
        '''    STRFTIME(&apos;%d/%m/%Y&apos;, PAYMENTTERM.CREATIONDATE) As &apos;Data&apos;,
        '''    PAYMENTTERM.NAME AS &apos;Nome&apos;,
        '''    CASE PAYMENTTERM.TYPEOFDAYSID
        '''        WHEN 0 THEN &apos;Dias Úteis&apos;
        '''        WHEN 1 THEN &apos;Dias Corridos&apos;
        '''    END AS &apos;Tipo de Prazo&apos;
        '''FROM PAYMENTTERM
        '''WHERE
        '''    IFNULL(PAYMENTTERM.ID, &apos;&apos;) LIKE @ID AND
        '''    IFNULL(PAYMENTTERM.STATUSID, &apos;&apos;) LIKE @STATUSID AND
        '''    IFNULL(PAYMENTTERM.NAME,  [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PaymentTermFilter() As String
            Get
                Return ResourceManager.GetString("PaymentTermFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO PAYMENTTERM
        ''' (
        '''    STATUSID,
        '''    CREATIONDATE,
        '''    NAME,
        '''    TYPEOFDAYSID,
        '''    USERID
        ''' )
        '''VALUES
        ''' (
        '''    @STATUSID,
        '''    @CREATIONDATE,
        '''    @NAME,
        '''    @TYPEOFDAYSID,
        '''    @USERID
        ''' );.
        '''</summary>
        Friend ReadOnly Property PaymentTermInsert() As String
            Get
                Return ResourceManager.GetString("PaymentTermInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT	
        '''    PAYMENTTERM.ID,
        '''    PAYMENTTERM.STATUSID,
        '''    PAYMENTTERM.CREATIONDATE,
        '''    PAYMENTTERM.NAME,
        '''    PAYMENTTERM.TYPEOFDAYSID,
        '''    PAYMENTTERM.USERID
        '''FROM PAYMENTTERM
        '''WHERE PAYMENTTERM.ID = @ID.
        '''</summary>
        Friend ReadOnly Property PaymentTermSelect() As String
            Get
                Return ResourceManager.GetString("PaymentTermSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PAYMENTTERM SET
        '''    STATUSID = @STATUSID,
        '''    NAME = @NAME,
        '''    TYPEOFDAYSID = @TYPEOFDAYSID,
        '''    USERID = @USERID
        '''WHERE PAYMENTTERM.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PaymentTermUpdate() As String
            Get
                Return ResourceManager.GetString("PaymentTermUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Person() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Person", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM PERSONCONTACT
        '''WHERE PERSONCONTACT.PERSONID = @PERSONID
        '''    AND PERSONCONTACT.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PersonContactDelete() As String
            Get
                Return ResourceManager.GetString("PersonContactDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO PERSONCONTACT
        ''' (
        '''    SEQ,
        '''    PERSONID,
        '''    NAME,
        '''    JOBTITLE,
        '''    PHONE1,
        '''    PHONE2,
        '''    PHONE3,
        '''    EMAIL1,
        '''    EMAIL2
        ''' )
        '''VALUES
        ''' (
        '''    @SEQ,
        '''    @PERSONID,
        '''    @NAME,
        '''    @JOBTITLE,
        '''    @PHONE1,
        '''    @PHONE2,
        '''    @PHONE3,
        '''    @EMAIL1,
        '''    @EMAIL2
        ''' );.
        '''</summary>
        Friend ReadOnly Property PersonContactInsert() As String
            Get
                Return ResourceManager.GetString("PersonContactInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    PERSON.LASTCONTACTSEQ FROM PERSON WHERE PERSON.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PersonContactLastSeq() As String
            Get
                Return ResourceManager.GetString("PersonContactLastSeq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    PERSONCONTACT.ID,
        '''    PERSONCONTACT.SEQ,
        '''    PERSONCONTACT.PERSONID,
        '''    PERSONCONTACT.NAME,
        '''    PERSONCONTACT.JOBTITLE,
        '''    PERSONCONTACT.PHONE1,
        '''    PERSONCONTACT.PHONE2,
        '''    PERSONCONTACT.PHONE3,
        '''    PERSONCONTACT.EMAIL1,
        '''    PERSONCONTACT.EMAIL2
        '''FROM PERSONCONTACT
        '''WHERE PERSONCONTACT.PERSONID = @ID;.
        '''</summary>
        Friend ReadOnly Property PersonContactSelect() As String
            Get
                Return ResourceManager.GetString("PersonContactSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PERSONCONTACT SET
        '''    NAME = @NAME,
        '''    JOBTITLE = @JOBTITLE,
        '''    PHONE1 = @PHONE1,
        '''    PHONE2 = @PHONE2,
        '''    PHONE3 = @PHONE3,
        '''    EMAIL1 = @EMAIL1,
        '''    EMAIL2 = @EMAIL2
        '''WHERE PERSONCONTACT.PERSONID = @PERSONID
        '''     AND PERSONCONTACT.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PersonContactUpdate() As String
            Get
                Return ResourceManager.GetString("PersonContactUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PERSON SET
        '''     DEFAULTCONTACTID = @DEFAULTCONTACTID
        '''WHERE PERSON.ID = @PERSONID;.
        '''</summary>
        Friend ReadOnly Property PersonDefaultContactUpdate() As String
            Get
                Return ResourceManager.GetString("PersonDefaultContactUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM PERSON
        '''WHERE PERSON.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PersonDelete() As String
            Get
                Return ResourceManager.GetString("PersonDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    PERSON.ID,
        '''    CASE PERSON.STATUSID
        '''        WHEN 0 THEN &apos;Ativo&apos;
        '''        WHEN 1 THEN &apos;Inativo&apos;
        '''    END AS &apos;Status&apos;,
        '''    STRFTIME(&apos;%d/%m/%Y&apos;, PERSON.CREATIONDATE) As &apos;Data&apos;,
        '''    CASE PERSON.ENTITYTYPEID
        '''        WHEN 0 THEN &apos;Pessoa Física&apos;
        '''        WHEN 1 THEN &apos;Pessoa Jurídica&apos;
        '''    END AS &apos;Entidade&apos;,
        '''    CASE PERSON.ISPROVIDER
        '''        WHEN 0 THEN &apos;Não&apos;
        '''        ELSE &apos;Sim&apos;
        '''    END AS &apos;Fornecedor&apos;,
        '''    CASE PERSON.ISCUSTOMER
        '''        WHEN 0 THEN &apos;Não&apos;
        '''        ELSE &apos;Sim&apos;
        '''    END AS &apos;Clie [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PersonFilter() As String
            Get
                Return ResourceManager.GetString("PersonFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO PERSON
        ''' (
        '''    STATUSID,
        '''    CREATIONDATE,
        '''    ENTITYTYPEID,
        '''    ISPROVIDER,
        '''    ISCUSTOMER,
        '''    ISCARRIER,
        '''    NAME,
        '''    BUSINESSNAME,
        '''    DOCUMENT1,
        '''    DOCUMENT2,
        '''    DOCUMENT3,
        '''    ZIPCODE,
        '''    ADDRESS,
        '''    NUMBER,
        '''    COMPLEMENT,
        '''    DISTRICT,
        '''    CITY,
        '''    STATE,
        '''    NOTE,
        '''    DEFAULTCONTACTID,
        '''    USERID
        ''' )
        '''VALUES
        ''' (
        '''    @STATUSID,
        '''    @CREATIONDATE,
        '''    @ENTITYTYPEID,
        '''    @ISPROVIDER,
        '''    @ISCUSTOMER,
        '''    @ISCARRIER,
        '''    @NAME,
        '''    @BUSINESSNAME,
        '''    @DOCUMENT1,
        '''    @DOCUMENT2,
        '''    @DOCUM [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PersonInsert() As String
            Get
                Return ResourceManager.GetString("PersonInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PERSON SET
        '''    LASTCONTACTSEQ = @LASTCONTACTSEQ
        '''WHERE PERSON.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PersonLastContactSeqUpdate() As String
            Get
                Return ResourceManager.GetString("PersonLastContactSeqUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT	
        '''    PERSON.ID,
        '''    PERSON.STATUSID,
        '''    PERSON.CREATIONDATE,
        '''    PERSON.ENTITYTYPEID,
        '''    PERSON.ISPROVIDER,
        '''    PERSON.ISCUSTOMER,
        '''    PERSON.ISCARRIER,
        '''    PERSON.NAME,
        '''    PERSON.BUSINESSNAME,
        '''    PERSON.DOCUMENT1,
        '''    PERSON.DOCUMENT2,
        '''    PERSON.DOCUMENT3,
        '''    PERSON.ZIPCODE,
        '''    PERSON.ADDRESS,
        '''    PERSON.NUMBER,
        '''    PERSON.COMPLEMENT,
        '''    PERSON.DISTRICT,
        '''    PERSON.CITY,
        '''    PERSON.STATE,
        '''    PERSON.NOTE,
        '''    PERSON.DEFAULTCONTACTID,
        '''    PERSON.LASTCONTACTSEQ,
        '''    PERSON.USERID
        '''FROM PERSON
        '''W [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PersonSelect() As String
            Get
                Return ResourceManager.GetString("PersonSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PERSON SET
        '''    STATUSID = @STATUSID,
        '''    ENTITYTYPEID = @ENTITYTYPEID,
        '''    ISPROVIDER = @ISPROVIDER,
        '''    ISCUSTOMER = @ISCUSTOMER,
        '''    ISCARRIER = @ISCARRIER,
        '''    NAME = @NAME,
        '''    BUSINESSNAME = @BUSINESSNAME,
        '''    DOCUMENT1 = @DOCUMENT1,
        '''    DOCUMENT2 = @DOCUMENT2,
        '''    DOCUMENT3 = @DOCUMENT3,
        '''    ZIPCODE = @ZIPCODE,
        '''    ADDRESS = @ADDRESS,
        '''    NUMBER = @NUMBER,
        '''    COMPLEMENT = @COMPLEMENT,
        '''    DISTRICT = @DISTRICT,
        '''    CITY = @CITY,
        '''    STATE = @STATE,
        '''    NOTE = @NOTE,
        '''    DEFAULTCONTACTID = @DEFA [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PersonUpdate() As String
            Get
                Return ResourceManager.GetString("PersonUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Preferences() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Preferences", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Purchase_Order() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Purchase_Order", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PURCHASEORDER SET
        '''    SITUATIONID = @SITUATIONID
        '''WHERE PURCHASEORDER.ID = @ID.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderChangeSituation() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderChangeSituation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM PURCHASEORDER
        '''WHERE PURCHASEORDER.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderDelete() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    PURCHASEORDER.ID,
        '''    CASE PURCHASEORDER.STATUSID
        '''        WHEN 0 THEN &apos;Pendente&apos;
        '''        WHEN 1 THEN &apos;Parc. Recebido&apos;
        '''        WHEN 2 THEN &apos;Recebido&apos;
        '''        WHEN 3 THEN &apos;Cancelado&apos;
        '''    END AS &apos;Status&apos;,
        '''    CASE PURCHASEORDER.SITUATIONID
        '''        WHEN 0 THEN &apos;Não Aprovado&apos;
        '''        WHEN 1 THEN &apos;Aprovado&apos;
        '''    END AS &apos;Situação&apos;,
        '''    STRFTIME(&apos;%d/%m/%Y&apos;, PURCHASEORDER.CREATIONDATE) As &apos;Data&apos;,
        '''    QUOTATION.ID AS &apos;Cotação&apos;,
        '''    COSTSHARING.NAME AS &apos;Centro de Custo&apos;,
        '''    PERSON.NAME AS &apos;Fornecedor&apos;,
        '''     [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderFilter() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO PURCHASEORDER
        ''' (
        '''    STATUSID,
        '''    SITUATIONID,
        '''    CREATIONDATE,
        '''    QUOTATIONID,
        '''    COSTSHARINGID,
        '''    COSTSHARINGLOCALID,
        '''    PERSONID,
        '''    CONTACT,
        '''    PHONE,
        '''    EMAIL,
        '''    PAYMENTTERMID,
        '''    CARRIERID,
        '''    CARRIERTYPEID,
        '''    CARRIERPRICE,
        '''    DISCOUNT,
        '''    EXPENSE,
        '''    ICMSST,
        '''    INITIALDELIVERY,
        '''    FINALDELIVERY,
        '''    EXTERNALNOTE,
        '''    INTERNALNOTE,
        '''    USERID
        ''' )
        '''VALUES
        ''' (
        '''    @STATUSID,
        '''    @SITUATIONID,
        '''    @CREATIONDATE,
        '''    @QUOTATIONID,
        '''    @COSTSHARINGID,
        '''    @COSTSHARINGLOCALID,
        ''' [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderInsert() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM PURCHASEORDERITEM
        '''WHERE PURCHASEORDERITEM.PURCHASEORDERID = @PURCHASEORDERID
        '''    AND PURCHASEORDERITEM.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderItemDelete() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderItemDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO PURCHASEORDERITEM
        ''' (
        '''    SEQ,
        '''    PURCHASEORDERID,
        '''    ITEMID,
        '''    QUANTITY,
        '''    ITEMUNITID,
        '''    PRICE,
        '''    DISCOUNT,
        '''    COMPLEMENT,   
        '''    IPI,
        '''    ICMS
        ''' )
        '''VALUES
        ''' (
        '''    @SEQ,
        '''    @PURCHASEORDERID,
        '''    @ITEMID,
        '''    @QUANTITY,
        '''    @ITEMUNITID,
        '''    @PRICE,
        '''    @DISCOUNT,
        '''    @COMPLEMENT,   
        '''    @IPI,
        '''    @ICMS
        ''' );.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderItemInsert() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderItemInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    PURCHASEORDERITEM.ID,
        '''    PURCHASEORDERITEM.SEQ,
        '''    PURCHASEORDERITEM.DELIVERYDATE,
        '''    PURCHASEORDERITEM.PURCHASEORDERID,
        '''    PURCHASEORDERITEM.ITEMID,
        '''    PURCHASEORDERITEM.ITEMUNITID,
        '''    PURCHASEORDERITEM.QUANTITY,
        '''    ITEMUNIT.INITIALS AS &apos;UNITNAME&apos;,
        '''    ITEM.NAME AS &apos;ITEMNAME&apos;,
        '''    PURCHASEORDERITEM.PRICE,
        '''    PURCHASEORDERITEM.DISCOUNT,
        '''    PURCHASEORDERITEM.COMPLEMENT,
        '''    PURCHASEORDERITEM.IPI,
        '''    PURCHASEORDERITEM.ICMS
        '''FROM PURCHASEORDERITEM
        '''LEFT JOIN ITEMUNIT ON ITEMUNIT.ID = PURCHAS [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderItemSelect() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderItemSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PURCHASEORDERITEM SET
        '''    ITEMID = @ITEMID,
        '''    QUANTITY = @QUANTITY,
        '''    ITEMUNITID = @ITEMUNITID,
        '''    PRICE = @PRICE,
        '''    DISCOUNT = @DISCOUNT,
        '''    COMPLEMENT = @COMPLEMENT,
        '''    IPI = @IPI,
        '''    ICMS = @ICMS
        '''WHERE PURCHASEORDERITEM.PURCHASEORDERID = @PURCHASEORDERID
        '''    AND PURCHASEORDERITEM.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderItemUpdate() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderItemUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PURCHASEORDER SET
        '''    LASTITEMSEQ = @LASTITEMSEQ
        '''WHERE PURCHASEORDER.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderLastItemSeqUpdate() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderLastItemSeqUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT	
        '''    PURCHASEORDER.ID,
        '''    PURCHASEORDER.STATUSID,
        '''    PURCHASEORDER.SITUATIONID,
        '''    PURCHASEORDER.CREATIONDATE,
        '''    PURCHASEORDER.QUOTATIONID,
        '''    PURCHASEORDER.COSTSHARINGID,
        '''    PURCHASEORDER.COSTSHARINGLOCALID,
        '''    PURCHASEORDER.PERSONID,
        '''    PURCHASEORDER.CONTACT,
        '''    PURCHASEORDER.PHONE,
        '''    PURCHASEORDER.EMAIL,
        '''    PURCHASEORDER.PAYMENTTERMID,
        '''    PURCHASEORDER.CARRIERID,
        '''    PURCHASEORDER.CARRIERTYPEID,
        '''    PURCHASEORDER.CARRIERPRICE,
        '''    PURCHASEORDER.DISCOUNT,
        '''    PURCHASEORDER.EXPENSE,
        '''   [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderSelect() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE PURCHASEORDER SET
        '''    STATUSID = @STATUSID,
        '''    SITUATIONID = @SITUATIONID,
        '''    COSTSHARINGID = @COSTSHARINGID,
        '''    COSTSHARINGLOCALID = @COSTSHARINGLOCALID,
        '''    PERSONID = @PERSONID,
        '''    CONTACT = @CONTACT,
        '''    PHONE = @PHONE,
        '''    EMAIL = @EMAIL,
        '''    PAYMENTTERMID = @PAYMENTTERMID,
        '''    CARRIERID = @CARRIERID,
        '''    CARRIERTYPEID = @CARRIERTYPEID,
        '''    CARRIERPRICE = @CARRIERPRICE,
        '''    DISCOUNT = @DISCOUNT,
        '''    EXPENSE = @EXPENSE,
        '''    ICMSST = @ICMSST,
        '''    INITIALDELIVERY = @INITIALDELIVERY,
        '''    FINALDE [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property PurchaseOrderUpdate() As String
            Get
                Return ResourceManager.GetString("PurchaseOrderUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Quotation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Quotation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    QUOTATIONANSWER.ID,
        '''    QUOTATIONANSWER.QUOTATIONID,
        '''    QUOTATIONANSWER.PROVIDERID,
        '''    QUOTATIONANSWER.ITEMID,
        '''    QUOTATIONANSWER.NOTE,
        '''    QUOTATIONANSWER.PRICE,
        '''    QUOTATIONANSWER.ICMS,
        '''    QUOTATIONANSWER.ICMSST,
        '''    QUOTATIONANSWER.IPI,
        '''    QUOTATIONANSWER.DISCOUNT,
        '''    QUOTATIONANSWER.EXPENSE
        '''FROM QUOTATIONANSWER
        '''WHERE QUOTATIONID = @ID;.
        '''</summary>
        Friend ReadOnly Property QuotationAnswerSelect() As String
            Get
                Return ResourceManager.GetString("QuotationAnswerSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    QUOTATION.ID,
        '''    QUOTATION.STATUSID,
        '''    QUOTATION.CREATIONDATE,
        '''    QUOTATION.COSTID,
        '''    QUOTATION.OFFERTYPEID,
        '''    QUOTATION.NOTE,
        '''    QUOTATION.USERID
        '''FROM QUOTATION
        '''WHERE QUOTATION.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property QuotationSelect() As String
            Get
                Return ResourceManager.GetString("QuotationSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO REPORT
        '''(
        '''    PATH
        ''')
        '''VALUES
        '''(
        '''    @PATH
        ''');.
        '''</summary>
        Friend ReadOnly Property ReportInsert() As String
            Get
                Return ResourceManager.GetString("ReportInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    REPORT.ID,
        '''    REPORT.REPORTGROUP,
        '''    REPORT.NAME,
        '''    REPORT.PATH,
        '''    REPORT.DIRECT
        '''FROM REPORT
        '''ORDER BY REPORT.REPORTGROUP, REPORT.NAME;.
        '''</summary>
        Friend ReadOnly Property ReportSelect() As String
            Get
                Return ResourceManager.GetString("ReportSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    USER.ID,
        '''    USER.PASSWORD
        '''FROM USER
        '''WHERE USER.USERNAME = @USERNAME;.
        '''</summary>
        Friend ReadOnly Property SessionCheckUser() As String
            Get
                Return ResourceManager.GetString("SessionCheckUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a  SELECT
        '''    LAST_INSERT_ROWID() AS NEWID;.
        '''</summary>
        Friend ReadOnly Property SqlLastID() As String
            Get
                Return ResourceManager.GetString("SqlLastID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tables() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tables", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM USER
        '''WHERE USER.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property UserDelete() As String
            Get
                Return ResourceManager.GetString("UserDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT
        '''    USER.ID,
        '''    CASE USER.STATUSID
        '''        WHEN 0 THEN &apos;Ativo&apos;
        '''        WHEN 1 THEN &apos;Inativo&apos;
        '''    END AS &apos;Status&apos;,
        '''    STRFTIME(&apos;%d/%m/%Y&apos;,USER.CREATIONDATE) As &apos;Data&apos;,
        '''    USER.NAME AS &apos;Nome&apos;,
        '''    USER.USERNAME AS &apos;Usuário&apos;,
        '''    USER.PHONE AS &apos;Telefone&apos;,
        '''    USER.EMAIL AS &apos;E-Mail&apos;
        '''FROM USER
        '''WHERE
        '''    USER.ID &lt;&gt; 1 AND
        '''    IFNULL(USER.ID, &apos;&apos;) LIKE @ID AND
        '''    IFNULL(USER.STATUSID, &apos;&apos;) LIKE @STATUSID AND
        '''    IFNULL(USER.NAME, &apos;&apos;) LIKE @NAME AND
        '''    IFNULL(USER.USERNAME, &apos;&apos;) LIKE @USERNAME AND
        '''    IFNUL [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property UserFilter() As String
            Get
                Return ResourceManager.GetString("UserFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO USER
        ''' (
        '''    STATUSID,
        '''    CREATIONDATE,
        '''    USERNAME,
        '''    PASSWORD,
        '''    NAME,
        '''    EMAIL,
        '''    PHONE,
        '''    USERID
        ''' )
        '''VALUES
        ''' (
        '''    @STATUSID,
        '''    @CREATIONDATE,
        '''    @USERNAME,
        '''    @PASSWORD,
        '''    @NAME,
        '''    @EMAIL,
        '''    @PHONE,
        '''    @USERID
        ''' );.
        '''</summary>
        Friend ReadOnly Property UserInsert() As String
            Get
                Return ResourceManager.GetString("UserInsert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Username() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Username", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a SELECT USER.ID,
        '''    USER.STATUSID,
        '''    USER.CREATIONDATE,
        '''    USER.USERNAME,
        '''    USER.PASSWORD,
        '''    USER.NAME,
        '''    USER.EMAIL,
        '''    USER.PHONE,
        '''    USER.USERID
        '''FROM USER
        '''JOIN USER AS USER2 ON USER.ID = USER2.ID
        '''WHERE USER.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property UserSelect() As String
            Get
                Return ResourceManager.GetString("UserSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a UPDATE USER SET
        '''    USERID = @USERID,
        '''    STATUSID = @STATUSID,
        '''    USERNAME = @USERNAME,
        '''    NAME = @NAME,
        '''    EMAIL = @EMAIL,
        '''    PHONE = @PHONE
        '''WHERE USER.ID = @ID;.
        '''</summary>
        Friend ReadOnly Property UserUpdate() As String
            Get
                Return ResourceManager.GetString("UserUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property View() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("View", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ZipCode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZipCode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
